CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, section_id INTEGER, starttime INTEGER, endtime INTEGER, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS polls (id INTEGER, session_id INTEGER, timestamp INTEGER, duration INTEGER, type INTEGER, points INTEGER, question TEXT, answers TEXT);
CREATE TABLE IF NOT EXISTS sections (id INTEGER PRIMARY KEY AUTOINCREMENT, instructor_id INTEGER, channel_id INTEGER UNIQUE, role_id INTEGER UNIQUE, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS responses (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, poll_id INTEGER, correct INTEGER, response TEXT, UNIQUE(user_id, poll_id));
CREATE TABLE IF NOT EXISTS students (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER UNIQUE, univ_id TEXT, section_id INTEGER);